/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.LoginForm;

import com.mycompany.mavenproject1.LoginForm.Login;
import com.mycompany.mavenproject1.ConnectionQuery.DatabaseConnector;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author John Kyle G. Mistas
 */
public class ConfirmForgot extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmForgot
     */
    public ConfirmForgot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     public static String idCheck(String empid) {
        try (Connection conn = DatabaseConnector.getConnection()) {
            String query = "SELECT employeeid FROM users_acc WHERE employeeid = ?";
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setString(1, empid);
            ResultSet rs = pstmt.executeQuery();
            
            if (rs.next()){
                 // Get the value from the columnIndex (assuming it's a String) of the current row
                 String text = rs.getString(1);
                 // Return the retrieved value as a String
                 return text;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        // Return the retrieved value as null
        return null;
     }
     
      public static String welcomeUser(String empid) {
        try (Connection conn = DatabaseConnector.getConnection()) {
            String query = "SELECT firstname FROM users_acc WHERE employeeid = ?";
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setString(1, empid);
            ResultSet rs = pstmt.executeQuery();
            
            if (rs.next()){
                 // Get the value from the columnIndex (assuming it's a String) of the current row
                 String text = rs.getString(1);
                 // Return the retrieved value as a String
                 return text;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        // Return the retrieved value as null
        return null;
     }
      
       public static String welcomeUserlast(String empid) {
        try (Connection conn = DatabaseConnector.getConnection()) {
            String query = "SELECT lastname FROM users_acc WHERE employeeid = ?";
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setString(1, empid);
            ResultSet rs = pstmt.executeQuery();
            
            if (rs.next()){
                 // Get the value from the columnIndex (assuming it's a String) of the current row
                 String text = rs.getString(1);
                  // Return the retrieved value as a String
                 return text;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        // Return the retrieved value as null
        return null;
     }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        idText = new javax.swing.JTextField();
        Exitbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Enter Employee ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 290, 140, 30);

        jButton1.setBackground(null);
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Kyle G. Mistas\\Downloads\\1check-mark.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 320, 30, 40);

        idText.setBackground(null);
        idText.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        idText.setForeground(new java.awt.Color(204, 204, 204));
        idText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idText.setText("Employee ID");
        idText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51), 2));
        idText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idTextFocusLost(evt);
            }
        });
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });
        jPanel1.add(idText);
        idText.setBounds(80, 320, 220, 40);

        Exitbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Kyle G. Mistas\\Downloads\\1button.png")); // NOI18N
        Exitbtn.setContentAreaFilled(false);
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Exitbtn);
        Exitbtn.setBounds(370, 0, 30, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Kyle G. Mistas\\Downloads\\3GFIILOGO-1.png")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 10, 210, 210);

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 255, 102));
        jLabel15.setText("green");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(120, 220, 70, 32);

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 51));
        jLabel16.setText("future");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(180, 220, 100, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel17.setText("Innovation, Inc.");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(130, 240, 170, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 490);

        setSize(new java.awt.Dimension(414, 457));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTextFocusGained
        // TODO add your handling code here:
         Border bnorm = BorderFactory.createLineBorder(Color.gray);
        idText.setBorder(bnorm);
//        error.setText("");
        if(idText.getText().equals("Employee ID")){
            idText.setText(null);
            idText.requestFocus();
            idText.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_idTextFocusGained

    private void idTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTextFocusLost
        // TODO add your handling code here:
        if(idText.getText().length()==0){
            idText.setText("Employee ID");
        }
    }//GEN-LAST:event_idTextFocusLost

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Border bnorm = BorderFactory.createLineBorder(Color.gray);
        Border bred = BorderFactory.createLineBorder(Color.red);
        String idhold = idText.getText();
        
        if(idhold.equals("Employee ID")){
            idText.setBorder(bred);
            JOptionPane.showMessageDialog(null, "No Input ID","Warning",JOptionPane.ERROR_MESSAGE);
            
        }else if(idhold.equals("")){
            idText.setBorder(bred);
            JOptionPane.showMessageDialog(null, "No Input ID","Warning",JOptionPane.ERROR_MESSAGE);
             
        }else{
        String idExist = idCheck(idhold);
        if(idhold.equals(idExist)){
            idText.setBorder(bnorm);
            String firstName = welcomeUser(idhold);
            String lastName = welcomeUserlast(idhold);
            
            ForgotPassForm fFrom = new ForgotPassForm();
            fFrom.first.setText(firstName);
            fFrom.last.setText(lastName);
            dispose();
            fFrom.setVisible(true);
            
        }else{
            idText.setBorder(bred);
            JOptionPane.showMessageDialog(null, "ID Not Found","Warning",JOptionPane.ERROR_MESSAGE);
        }
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_ExitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmForgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmForgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmForgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmForgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmForgot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exitbtn;
    private javax.swing.JTextField idText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
