/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.RegisterForm;

/**
 *
 * @author John Kyle G. Mistas
 */
public class AboutInfo extends javax.swing.JFrame {

    /**
     * Creates new form AboutInfo
     */
    public AboutInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aboutUsArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        vissionArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        missionArea = new javax.swing.JTextArea();
        Exitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 255, 102));
        jLabel15.setText("green");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(60, 200, 70, 32);

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 51));
        jLabel16.setText("future");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(120, 200, 100, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel17.setText("Innovation, Inc.");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(70, 220, 170, 32);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Kyle G. Mistas\\Downloads\\3GFIILOGO-1.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 20, 210, 180);

        jPanel1.setLayout(null);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "About Us", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N

        aboutUsArea.setEditable(false);
        aboutUsArea.setBackground(new java.awt.Color(204, 255, 204));
        aboutUsArea.setColumns(20);
        aboutUsArea.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        aboutUsArea.setRows(5);
        aboutUsArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(aboutUsArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 50, 290, 230);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Vission", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N

        vissionArea.setEditable(false);
        vissionArea.setBackground(new java.awt.Color(204, 255, 204));
        vissionArea.setColumns(20);
        vissionArea.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        vissionArea.setRows(5);
        jScrollPane2.setViewportView(vissionArea);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(310, 320, 270, 200);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Mission", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N

        missionArea.setEditable(false);
        missionArea.setBackground(new java.awt.Color(204, 255, 204));
        missionArea.setColumns(20);
        missionArea.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        missionArea.setRows(5);
        jScrollPane3.setViewportView(missionArea);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(20, 320, 260, 200);

        Exitbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Kyle G. Mistas\\Downloads\\1button.png")); // NOI18N
        Exitbtn.setContentAreaFilled(false);
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Exitbtn);
        Exitbtn.setBounds(570, 0, 30, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 530);

        setSize(new java.awt.Dimension(600, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        // TODO add your handling code here:
        Register2acc reg = new Register2acc();
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_ExitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exitbtn;
    public javax.swing.JTextArea aboutUsArea;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextArea missionArea;
    public javax.swing.JTextArea vissionArea;
    // End of variables declaration//GEN-END:variables
}
