/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.UserDash;

import com.mycompany.mavenproject1.ConnectionQuery.DataHandler;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author John Kyle G. Mistas
 */
public class LeaveForm extends javax.swing.JFrame {

    /**
     * Creates new form LeaveForm
     */
    public LeaveForm() {
        initComponents();
        printbtn.setVisible(false);
        submitbtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        empname = new javax.swing.JTextField();
        leavedate = new javax.swing.JTextField();
        empid = new javax.swing.JTextField();
        reasonsLeave = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        leavearea = new javax.swing.JTextArea();
        generatebtn = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        printbtn = new javax.swing.JButton();
        submitbtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        empname.setEditable(false);
        empname.setBackground(null);
        empname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        empname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        empname.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(51, 255, 0)), "NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 12), new java.awt.Color(0, 102, 0))); // NOI18N
        empname.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        empname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empnameActionPerformed(evt);
            }
        });
        jPanel1.add(empname);
        empname.setBounds(50, 150, 280, 40);

        leavedate.setEditable(false);
        leavedate.setBackground(null);
        leavedate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        leavedate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        leavedate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(51, 255, 0)), "DATE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 12), new java.awt.Color(0, 102, 0))); // NOI18N
        leavedate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(leavedate);
        leavedate.setBounds(50, 220, 280, 40);

        empid.setEditable(false);
        empid.setBackground(null);
        empid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        empid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        empid.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(51, 255, 0)), "EMPLOYEE ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 12), new java.awt.Color(0, 102, 0))); // NOI18N
        empid.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(empid);
        empid.setBounds(50, 300, 280, 40);

        reasonsLeave.setBackground(null);
        reasonsLeave.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        reasonsLeave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Illness or Injury", "Family Medical Emergency", "Personal Tragedy", "Accidents or Emergencies", "Legal Obligations", "Personal Mental Health Concerns", "Domestic Violence or Safety Concerns" }));
        reasonsLeave.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(51, 255, 0)), "REASON", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 12), new java.awt.Color(0, 102, 0))); // NOI18N
        reasonsLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasonsLeaveActionPerformed(evt);
            }
        });
        jPanel1.add(reasonsLeave);
        reasonsLeave.setBounds(50, 360, 280, 50);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Leave Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N

        leavearea.setEditable(false);
        leavearea.setColumns(20);
        leavearea.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        leavearea.setRows(5);
        jScrollPane1.setViewportView(leavearea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(480, 40, 350, 420);

        generatebtn.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        generatebtn.setText("Generate");
        generatebtn.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 255, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 255, 0))); // NOI18N
        generatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(generatebtn);
        generatebtn.setBounds(70, 460, 110, 40);

        reset.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        reset.setText("Clear");
        reset.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 255, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 255, 0))); // NOI18N
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(320, 430, 100, 30);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Kyle G. Mistas\\Downloads\\1button.png")); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(820, 0, 30, 30);

        printbtn.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        printbtn.setText("Print");
        printbtn.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 255, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 255, 0))); // NOI18N
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });
        jPanel1.add(printbtn);
        printbtn.setBounds(720, 470, 100, 30);

        submitbtn.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        submitbtn.setText("submit");
        submitbtn.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 255, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 255, 0))); // NOI18N
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitbtn);
        submitbtn.setBounds(470, 470, 100, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 51));
        jLabel16.setText("future");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(160, 70, 100, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 255, 102));
        jLabel15.setText("green");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(100, 70, 70, 32);

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel17.setText("Innovation, Inc.");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(110, 90, 170, 32);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Kyle G. Mistas\\Downloads\\1GFIILOGO-1.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 30, 40, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 550);

        setSize(new java.awt.Dimension(850, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void empnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empnameActionPerformed

    private void generatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebtnActionPerformed
        // TODO add your handling code here:
        printbtn.setVisible(true);
        submitbtn.setVisible(true);

        leavearea.setText(" \t________________________________________________________\n");
        leavearea.setText(leavearea.getText()+" \t                    *         Leave Form          *\n");
        leavearea.setText(leavearea.getText()+"  \t            GREEN FUTURE INNOVATION, INC. \n");
        leavearea.setText(leavearea.getText()+"\t ________________________________________________________\n");
        String nameemp = empname.getText().toUpperCase();

        String selectedReason = (String) reasonsLeave.getSelectedItem();
        leavearea.setText(leavearea.getText()+"  "+"\n");
        leavearea.setText(leavearea.getText()+"  "+"\n");
        leavearea.setText(leavearea.getText()+"  "+"\n");
        leavearea.setText(leavearea.getText()+" \t Name : " + empname.getText()+"\n");
        leavearea.setText(leavearea.getText()+"  "+"\n");
        leavearea.setText(leavearea.getText()+" \t Date : " + leavedate.getText()+"\n");
        leavearea.setText(leavearea.getText()+"  "+"\n");
        leavearea.setText(leavearea.getText()+" \t Employee ID : " + empid.getText()+"\n");
        leavearea.setText(leavearea.getText()+"  "+"\n");
        leavearea.setText(leavearea.getText()+" \t Reason : " + selectedReason +"\n");
        leavearea.setText(leavearea.getText()+"  "+"\n");
        leavearea.setText(leavearea.getText()+"  "+"\n");
        leavearea.setText(leavearea.getText()+"  "+"\n");
        leavearea.setText(leavearea.getText()+"     \t                      "+nameemp+"\n");
        
        leavearea.setText(leavearea.getText()+"     \t           signature over printedname\n");
        leavearea.setText(leavearea.getText()+" \t________________________________________________________\n");
    }//GEN-LAST:event_generatebtnActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        leavearea.setText("");
        printbtn.setVisible(false);
//        empname.setText("");
//        leavedate.setText("");
//        empid.setText("");
        reasonsLeave.setSelectedItem(null);
        
        
    }//GEN-LAST:event_resetActionPerformed

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        // TODO add your handling code here:
        try{
            leavearea.print();
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_printbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int result = JOptionPane.showConfirmDialog(null, "Do you want to Quit Leave Form?", "Confirmation", JOptionPane.YES_NO_OPTION);

                // Check the user's choice
            if (result == JOptionPane.YES_OPTION) {
                
                dispose();
            }else{
                 JOptionPane.showMessageDialog(null, "Quit Canceled!","Mwssage",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
         int ans = JOptionPane.showConfirmDialog(null, "Are You Sure?","Confirm Quit?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(ans == JOptionPane.YES_OPTION) {
                String hrswrk1 = "LEAVE";
                String out = "EMERGENCY";

                String in = "LEAVE";
                String idHolder = empid.getText();
                Date currentTime = new Date();
                        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                        String dd = sdf.format(currentTime);

                boolean eXist = DataHandler.employeeLeave(in,out,hrswrk1,dd,idHolder);
                if(eXist){
                    DataHandler.employeeLeave(in,out,hrswrk1,dd,idHolder);
                    JOptionPane.showMessageDialog(null, "Successfully Submitted","Message",JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }else{
                    DataHandler.employeeLeave(in,out,hrswrk1,dd,idHolder);
                    JOptionPane.showMessageDialog(null, "Leave Successfully Submitted!","Message",JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
            }else{
           JOptionPane.showMessageDialog(null, "Quit Canceled!","Mwssage",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_submitbtnActionPerformed

    private void reasonsLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasonsLeaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reasonsLeaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaveForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField empid;
    public javax.swing.JTextField empname;
    private javax.swing.JButton generatebtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea leavearea;
    public javax.swing.JTextField leavedate;
    private javax.swing.JButton printbtn;
    private javax.swing.JComboBox<String> reasonsLeave;
    private javax.swing.JButton reset;
    private javax.swing.JButton submitbtn;
    // End of variables declaration//GEN-END:variables
}
