
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author John Kyle G. Mistas
 */
public class Input10 extends javax.swing.JFrame {

    /**
     * Creates new form Input10
     */
    public Input10() {
        initComponents();
       
        count.setEnabled(false);
        large.setEnabled(false);
        lowest.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        startbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        count = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        large = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lowest = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        startbtn.setText("Start");
        startbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbtnActionPerformed(evt);
            }
        });
        jPanel1.add(startbtn);
        startbtn.setBounds(110, 80, 72, 23);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Count Divisible by 3 :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 180, 150, 20);

        count.setBackground(new java.awt.Color(204, 204, 255));
        count.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countActionPerformed(evt);
            }
        });
        jPanel1.add(count);
        count.setBounds(190, 180, 80, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Largest Number :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 220, 140, 20);

        large.setBackground(new java.awt.Color(204, 204, 255));
        large.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        large.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeActionPerformed(evt);
            }
        });
        jPanel1.add(large);
        large.setBounds(190, 220, 80, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Lowest Number :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 260, 120, 20);

        lowest.setBackground(new java.awt.Color(204, 204, 255));
        lowest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lowest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowestActionPerformed(evt);
            }
        });
        jPanel1.add(lowest);
        lowest.setBounds(190, 260, 80, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Start Input :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 80, 80, 16);

        Clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear);
        Clear.setBounds(330, 320, 72, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 480, 450);

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbtnActionPerformed
        // TODO add your handling code here:{
        //intialize value for three category
         int maX = Integer.MIN_VALUE;
        int miN = Integer.MAX_VALUE;
        int divisible = 0;

        //Looping function
        for(int i = 1;i<=10;i++){
             String num = JOptionPane.showInputDialog(null,"Input "  + i + " number","Enter",JOptionPane.INFORMATION_MESSAGE);
             int inputnumber = Integer.parseInt(num);
             
//            System.out.println(num);
// condition for checking
            if(inputnumber % 3 == 0){
                divisible++;
            }
            if(inputnumber > maX){
                maX = inputnumber;
            }
            if (inputnumber < miN){
                miN = inputnumber;
            }
            //printing function
             String divisible1 = String.valueOf(divisible);
             count.setText(divisible1);
             String max = String.valueOf(maX);
             large.setText(max);
              String min = String.valueOf(miN);
             lowest.setText(min);
             
        }
       
    }//GEN-LAST:event_startbtnActionPerformed

    private void countActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countActionPerformed

    private void largeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largeActionPerformed

    private void lowestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lowestActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        count.setText("");
        large.setText("");
        lowest.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JTextField count;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField large;
    private javax.swing.JTextField lowest;
    private javax.swing.JButton startbtn;
    // End of variables declaration//GEN-END:variables
}
