/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.LoadingSplash;

/**
 *
 * @author John Kyle G. Mistas
 */
public class Loginscreen extends javax.swing.JFrame {

    /**
     * Creates new form Loginscreen
     */
    public Loginscreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        loadF = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        qoUtes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Kyle G. Mistas\\Downloads\\green-tick.gif")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 10, 230, 200);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Login Successfully!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 220, 240, 33);

        role.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        role.setForeground(new java.awt.Color(0, 255, 0));
        role.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        role.setText("role");
        jPanel1.add(role);
        role.setBounds(60, 290, 170, 30);

        loadF.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        loadF.setForeground(new java.awt.Color(0, 255, 0));
        loadF.setText("Kyle");
        jPanel1.add(loadF);
        loadF.setBounds(80, 260, 200, 26);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N

        qoUtes.setEditable(false);
        qoUtes.setBackground(new java.awt.Color(0, 0, 0));
        qoUtes.setColumns(20);
        qoUtes.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        qoUtes.setForeground(new java.awt.Color(0, 255, 0));
        qoUtes.setRows(5);
        qoUtes.setText("hi");
        qoUtes.setBorder(null);
        qoUtes.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jScrollPane1.setViewportView(qoUtes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 340, 240, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 300, 400);

        setSize(new java.awt.Dimension(300, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginscreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel loadF;
    public javax.swing.JTextArea qoUtes;
    public javax.swing.JLabel role;
    // End of variables declaration//GEN-END:variables
}
