/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.adminform;

import com.mycompany.mavenproject1.ConnectionQuery.DataHandler;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import java.time.LocalTime;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author John Kyle G. Mistas
 */
public class Addrec extends javax.swing.JFrame {

    /**
     * Creates new form Addrec
     */
    public Addrec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     private static Date parseMilitaryTime(String militaryTime, String formatPattern) {
        SimpleDateFormat dateFormat = new SimpleDateFormat(formatPattern);
        try {
            return dateFormat.parse(militaryTime);
        } catch (ParseException e) {
            return null;
        }
    }

    private static String convertToAMPM(Date date) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("hh:mm a");
        return dateFormat.format(date);
    }
    
    private static String formatDate(Date date) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        return dateFormat.format(date);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        empid = new javax.swing.JTextField();
        dateadd = new com.toedter.calendar.JDateChooser();
        timeoutadd = new lu.tudor.santec.jtimechooser.JTimeChooser();
        timeinadd = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel1.setText("Add Record");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 240, 120, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel2.setText("Time Out");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 350, 80, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel3.setText("Employee ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 430, 90, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel4.setText("Time In");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 350, 100, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel5.setText("Date");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 280, 50, 20);

        empid.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        empid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        empid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51), 2));
        jPanel1.add(empid);
        empid.setBounds(120, 450, 170, 40);

        dateadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51), 2));
        dateadd.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jPanel1.add(dateadd);
        dateadd.setBounds(120, 300, 140, 30);

        timeoutadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51), 2));
        timeoutadd.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jPanel1.add(timeoutadd);
        timeoutadd.setBounds(230, 370, 120, 40);

        timeinadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51), 2));
        timeinadd.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jPanel1.add(timeinadd);
        timeinadd.setBounds(40, 370, 120, 40);

        jButton1.setBackground(new java.awt.Color(51, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 490, 76, 27);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Kyle G. Mistas\\Downloads\\1button.png")); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(370, 0, 30, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Kyle G. Mistas\\Downloads\\3GFIILOGO-1.png")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 0, 210, 170);

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 255, 102));
        jLabel15.setText("green");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(120, 170, 70, 32);

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 51));
        jLabel16.setText("future");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(180, 170, 100, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel17.setText("Innovation, Inc.");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(130, 190, 170, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 550);

        setSize(new java.awt.Dimension(400, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        String formatPattern = "HH:mm:ss";
        Date selectedDate  = dateadd.getDate();
//       
        String in = timeinadd.getFormatedTime();
        String out = timeoutadd.getFormatedTime();
        String emp = empid.getText();
        
        if(selectedDate == null && emp.equals("")){
              JOptionPane.showMessageDialog(null,"Empty Input","Warning",JOptionPane.ERROR_MESSAGE);
        }else if(selectedDate == null){
             JOptionPane.showMessageDialog(null,"Plaese Select Date","Warning",JOptionPane.ERROR_MESSAGE);
        }else if(emp.equals("")){
             JOptionPane.showMessageDialog(null,"Plaese Employee Id","Warning",JOptionPane.ERROR_MESSAGE);
        }else{
            String formattedDate = formatDate(selectedDate);
            

            Date alltimein = parseMilitaryTime(in, formatPattern);
            String amPmTimein = convertToAMPM(alltimein);
  

            Date alltimeout = parseMilitaryTime(out, formatPattern);
            String amPmTimeout = convertToAMPM(alltimeout);
 

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("hh:mm a");

                LocalTime timeIn = LocalTime.parse(amPmTimein.toLowerCase(), formatter);
                LocalTime timeOut = LocalTime.parse(amPmTimeout.toLowerCase(), formatter);

            if (timeOut.isBefore(timeIn)) {
                timeOut = timeOut.plus(Duration.ofDays(1));
            }

            Duration duration = Duration.between(timeIn, timeOut);

            long totalHours = duration.toHours();

            String totalHourString = String.valueOf(totalHours);
            
            boolean eXist = DataHandler.addRecod(formattedDate, amPmTimein, amPmTimeout, totalHourString, emp);
                if(eXist){
                    JOptionPane.showMessageDialog(null,"User Id " + emp + " is Already In","Warning",JOptionPane.ERROR_MESSAGE);
                }else{
                    DataHandler.addRecod(formattedDate, amPmTimein, amPmTimeout, totalHourString, emp);
                    JOptionPane.showMessageDialog(null,"Total Hours " + totalHourString ,"Warning",JOptionPane.INFORMATION_MESSAGE);
                    JOptionPane.showMessageDialog(null,"Time Recorded Successfully","Warning",JOptionPane.INFORMATION_MESSAGE);
                    dispose();
        }
        }
            
//            JOptionPane.showMessageDialog(null, totalHourString);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addrec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateadd;
    private javax.swing.JTextField empid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private lu.tudor.santec.jtimechooser.JTimeChooser timeinadd;
    private lu.tudor.santec.jtimechooser.JTimeChooser timeoutadd;
    // End of variables declaration//GEN-END:variables
}
