/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.adminform;

import com.mycompany.mavenproject1.ConnectionQuery.DataHandler;
import com.mycompany.mavenproject1.Option;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author John Kyle G. Mistas
 */
public class ConfirmIdChange extends javax.swing.JFrame {

    /**
     * Creates new form ConfrimIdChange
     */
    public ConfirmIdChange() {
        initComponents();
        error.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        Exitbtn = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel1.setText("Enter UserName & Password First! ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 240, 210, 16);

        userTxt.setText("UserName");
        userTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51), 2));
        userTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userTxtFocusLost(evt);
            }
        });
        jPanel1.add(userTxt);
        userTxt.setBounds(70, 290, 200, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 340, 60, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("UserName");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 270, 60, 16);

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 410, 76, 27);

        error.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        error.setText("error");
        jPanel1.add(error);
        error.setBounds(120, 440, 120, 20);

        passwordText.setText("Password");
        passwordText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51), 2));
        passwordText.setEchoChar('\u0000');
        passwordText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTextFocusLost(evt);
            }
        });
        jPanel1.add(passwordText);
        passwordText.setBounds(70, 360, 200, 40);

        Exitbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Kyle G. Mistas\\Downloads\\1button.png")); // NOI18N
        Exitbtn.setContentAreaFilled(false);
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Exitbtn);
        Exitbtn.setBounds(320, 0, 30, 30);

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setText("show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(70, 410, 120, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Kyle G. Mistas\\Downloads\\3GFIILOGO-1.png")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 0, 210, 180);

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 255, 102));
        jLabel15.setText("green");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(90, 170, 70, 32);

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 51));
        jLabel16.setText("future");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(150, 170, 100, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel17.setText("Innovation, Inc.");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(100, 190, 170, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 540);

        setSize(new java.awt.Dimension(364, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTxtFocusGained
        // TODO add your handling code here:
          Border bnorm = BorderFactory.createLineBorder(Color.gray);
        userTxt.setBorder(bnorm);
        error.setText("");
        if(userTxt.getText().equals("UserName")){
            userTxt.setText(null);
            userTxt.requestFocus();
        }
    }//GEN-LAST:event_userTxtFocusGained

    private void userTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTxtFocusLost
        // TODO add your handling code here:
        if(userTxt.getText().length()==0){
            userTxt.setText("UserName");
        }
    }//GEN-LAST:event_userTxtFocusLost

    private void passwordTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextFocusGained
        // TODO add your handling code here:
         Border bnorm = BorderFactory.createLineBorder(Color.gray);
        passwordText.setBorder(bnorm);
        error.setText("");
        if(passwordText.getText().equals("Password")){
            passwordText.setText(null);
            passwordText.requestFocus();
            passwordText.setEchoChar('*');
        }
    }//GEN-LAST:event_passwordTextFocusGained

    private void passwordTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextFocusLost
        // TODO add your handling code here:
        if(passwordText.getText().length()==0){
            passwordText.setText("Password");
            passwordText.setEchoChar((char)0);
        }
    }//GEN-LAST:event_passwordTextFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Border bnorm = BorderFactory.createLineBorder(Color.gray);
          Border bred = BorderFactory.createLineBorder(Color.red);
        String user = userTxt.getText();
        String pass = passwordText.getText();
        
        
        if(user.equals("UserName") && pass.equals("Password")){
             userTxt.setBorder(bred);
             passwordText.setBorder(bred);
             
            error.setText("Empty Input");
             error.setVisible(true);
            
        }else if(user.equals("") && pass.equals("")){
             userTxt.setBorder(bred);
             passwordText.setBorder(bred);
             error.setText("Empty Input");
             error.setVisible(true);
             
        }else if(user.equals("UserName") ){
             userTxt.setBorder(bred);
             passwordText.setBorder(bnorm);
             error.setText("Required UserName");
             error.setVisible(true);
             
        }else if(user.equals("") ){
             userTxt.setBorder(bred);
             passwordText.setBorder(bnorm);
            error.setText("Required UserName");
            error.setVisible(true);
            
        }else if( pass.equals("Password")){
             userTxt.setBorder(bnorm);
             passwordText.setBorder(bred);
            error.setText("Required Password");
            error.setVisible(true);
            
        }else if( pass.equals("")){
             userTxt.setBorder(bnorm);
             passwordText.setBorder(bred);
            error.setText("Required Password");
            error.setVisible(true);
            
        }else{
            String first = DataHandler.welcomeUser(user);
            String last = DataHandler.welcomeUserlast(user);
            int rs = JOptionPane.showConfirmDialog(null, "Are you sure You Are " + first + " ?","Message", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            
            if(rs==JOptionPane.YES_OPTION){
               
                Idchange chg = new Idchange();
                chg.first.setText(first);
//                chg.last.setText(first);
                chg.last.setText(last);
                chg.setVisible(true);
                 dispose();
            }else{
                JOptionPane.showMessageDialog(null,"Submit Unsuccessfully","Message",JOptionPane.ERROR_MESSAGE);
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        // TODO add your handling code here:
        Option opt =  new Option();
        opt.setVisible(true);
        dispose();
    }//GEN-LAST:event_ExitbtnActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            //                    passwordText.setEchoChar('*');
            passwordText.setEchoChar((char) 0);
        } else {
            passwordText.setEchoChar('*');

        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmIdChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmIdChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmIdChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmIdChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmIdChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exitbtn;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
