/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.adminform;

import com.mycompany.mavenproject1.adminform.ConfirmIdChange;
import com.mycompany.mavenproject1.ConnectionQuery.DataHandler;
import javax.swing.JOptionPane;

/**
 *
 * @author John Kyle G. Mistas
 */
public class Idchange extends javax.swing.JFrame {

    /**
     * Creates new form Idchange
     */
    public Idchange() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        first = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        idsubmit = new javax.swing.JButton();
        oldIdTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Exitbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        last = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel1.setText("Enter Old Employee Id:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 290, 160, 20);

        first.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        first.setText("first");
        jPanel1.add(first);
        first.setBounds(110, 250, 70, 20);

        idTxt.setText("New Employee ID");
        idTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51), 2));
        idTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idTxtFocusLost(evt);
            }
        });
        jPanel1.add(idTxt);
        idTxt.setBounds(80, 380, 190, 40);

        idsubmit.setBackground(new java.awt.Color(102, 255, 102));
        idsubmit.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        idsubmit.setText("save");
        idsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(idsubmit);
        idsubmit.setBounds(240, 430, 79, 27);

        oldIdTxt.setText("Old Employee ID");
        oldIdTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51), 2));
        oldIdTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                oldIdTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                oldIdTxtFocusLost(evt);
            }
        });
        jPanel1.add(oldIdTxt);
        oldIdTxt.setBounds(80, 310, 190, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel2.setText("Enter New Employee Id:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 360, 160, 20);

        Exitbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Kyle G. Mistas\\Downloads\\1button.png")); // NOI18N
        Exitbtn.setContentAreaFilled(false);
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Exitbtn);
        Exitbtn.setBounds(320, 0, 30, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\John Kyle G. Mistas\\Downloads\\3GFIILOGO-1.png")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 0, 210, 180);

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 255, 102));
        jLabel15.setText("green");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(100, 180, 70, 32);

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 51));
        jLabel16.setText("future");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(160, 180, 100, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel17.setText("Innovation, Inc.");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(110, 200, 170, 32);

        last.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        last.setText("Last");
        jPanel1.add(last);
        last.setBounds(180, 250, 70, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 490);

        setSize(new java.awt.Dimension(364, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTxtFocusGained
        // TODO add your handling code here:
        if(idTxt.getText().equals("New Employee ID")){
            idTxt.setText(null);
            idTxt.requestFocus();
        }
    }//GEN-LAST:event_idTxtFocusGained

    private void idTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTxtFocusLost
        // TODO add your handling code here:
        if(idTxt.getText().length()==0){
            idTxt.setText("New Employee ID");
        }
    }//GEN-LAST:event_idTxtFocusLost

    private void idsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idsubmitActionPerformed
        // TODO add your handling code here:
        String idh = idTxt.getText();
        String old = oldIdTxt.getText();
        if(idh.equals("")&& old.equals("")){  
            JOptionPane.showMessageDialog(null,"Empty Input","Message",JOptionPane.ERROR_MESSAGE);
        }else if(idh.equals("New Employee ID") && old.equals("Old Employee ID")){
            JOptionPane.showMessageDialog(null,"Empty Input","Message",JOptionPane.ERROR_MESSAGE);
        }else if(old.equals("")){
            JOptionPane.showMessageDialog(null,"Required Old ID","Message",JOptionPane.ERROR_MESSAGE);
        }else if(old.equals("Old Employee ID")){
            JOptionPane.showMessageDialog(null,"Required Old ID","Message",JOptionPane.ERROR_MESSAGE);
        }else if(idh.equals("")){
            JOptionPane.showMessageDialog(null,"Required New ID","Message",JOptionPane.ERROR_MESSAGE);
        }else if(idh.equals("New Employee ID")){
            JOptionPane.showMessageDialog(null,"Required New ID","Message",JOptionPane.ERROR_MESSAGE);
        }else{
            String fname =  first.getText();
            String idnew = idTxt.getText();
                String check = DataHandler.checkidchange(fname);
         
            boolean exist = DataHandler.changeid(fname,idnew);

            
                if(check.equals(old)){
                    if(exist){
                        
                      JOptionPane.showMessageDialog(null,"Change Unuccessfully ID !","Message",JOptionPane.INFORMATION_MESSAGE);
                }else{
                         DataHandler.changeidRec(old,idnew);
                        
                         DataHandler.changeid(fname,idnew);
                         JOptionPane.showMessageDialog(null,"Change Successfully!","Message",JOptionPane.INFORMATION_MESSAGE);
                         
                         dispose();
                   
                }
            }else{
                        JOptionPane.showMessageDialog(null,"Error Id Not From " + fname,"Message",JOptionPane.ERROR_MESSAGE);
                        DataHandler.changeidRec(check,check);
                        DataHandler.changeid(fname,check);
                }
        }
    }//GEN-LAST:event_idsubmitActionPerformed

    private void oldIdTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_oldIdTxtFocusGained
        // TODO add your handling code here:
          if(oldIdTxt.getText().equals("Old Employee ID")){
            oldIdTxt.setText(null);
            oldIdTxt.requestFocus();
        }
        
    }//GEN-LAST:event_oldIdTxtFocusGained

    private void oldIdTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_oldIdTxtFocusLost
        // TODO add your handling code here:
        if(oldIdTxt.getText().length()==0){
            oldIdTxt.setText("Old Employee ID");
        }
    }//GEN-LAST:event_oldIdTxtFocusLost

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        // TODO add your handling code here:
        ConfirmIdChange chg = new ConfirmIdChange();
        chg.setVisible(true);
        dispose();
    }//GEN-LAST:event_ExitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Idchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Idchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Idchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Idchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Idchange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exitbtn;
    public javax.swing.JLabel first;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton idsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel last;
    private javax.swing.JTextField oldIdTxt;
    // End of variables declaration//GEN-END:variables
}
